const data = [
    'In the begining, GOD made the heavens',
    'Let there be light',
    'Call me in troble and I will answer you',
    'All good and perfect gifts comes from GOD',
    'Cast all your cares upon me for I care for you',
    'And they were filled with the Holy Spirit',
    'That i may be filled with the knowledge of his will',
    'He gives his angels charge over me',
    'Surely, goodness and mercies are following me',
    'Need wisdom? Ask of GOD who gives freely to all me',
    'For the Lord is good and his mercies is forever',
    'Greater is he that is in me than he that is the world',
    'But our sufficiency is of GOD',
    'Praying always in the Holy Spirit',
    'My spoken words to you are spirit and life',
    'Giving thanks to the father who delivered us to life',
    'Therefore glorify GOD in your spirit and your body',
    'I am the righteousness of GOD in christ',
    "Bless the Lord oh my soul and don't forget his benefits",
    'For God so loved the world that he gave his son',
    'But he that is joined with GOD is one spirit',
    'GOD is light and in him is no darkness at all',
    'Behold the manner of love the father has given us by making us sons',
    'I have fought a good fight of faith, I await my crown',
    'He will keep the feets of his saints',
    "GOD doesn't tempt any body, don't be decieved",
    'Surely all things must work out for the good of them that love me'
    'Let all your doings be done in charity',
    'I am not ashamed of the gospel',
    'And i will remember their sins no more',
    'That grace of GOD that brings salvation has appeared to all men',
    'That good thing committed to you, keep by the Holy Spirit',
    'The Lord is not slack concerning his promises',
    'For my strenght is made perfect in weakness',
    'Be kind towards one another, always forgiving',
    'And the light was the light of men',
    'Your sins are forgiven for his name sake',
    'GOD is a refuge for us',
    'Freely you have recieved, freely give',
    'He gave gifts unto men for the perfecting of the saints',
    'What the riches of his glory of his inheritance in christ',
    'Keep yourselves in the love of GOD',
    'We are saved not by works but by grace',
    'That the eyes of your understanding be enlightened',
    'Meditate on the word daily to have good success',
    'And the lord has laid on him the iniquity of us all',
    'For Abraham believe GOD and that made him righteous',
    'I wish you prosper just as your soul prospereth',
    'Likewise the spirit also helps our shortcomings',
    'Yet he has made with me an everlasting covenant',
    'GOD has given to us eternal life',
    'The lord is my sherperd, i shall not want',
    'For you are bought with a price',
    'The gift of GOD is eternal life',
    'He that is in christ is a new creation',
    'For every fear he gave us power, boldness and sound mind',
    'Let the word of Christ richly dwell in you',
    'If any man thirst let him come to me and drink',
    'Mercy rejoices agaiinst judgement',
    'Building up your most holy faith, praying in the Holy Spirit',
    'I can do all things through Christ',
    'As for his ministers, he made them flame of fire',
    'They looked unto him and they were lightened',
    'For by grace are we saved through faith',
    'For he has made Christ wisdom unto me',
    'Fear not, I will help you',
    'When you pray believe and you shall have what you want'
]

export default data
